fix: Used git to push tag

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -20,34 +20,39 @@ runs:
             https://api.github.com/repos/martoc/semver/releases/assets/150717342
         chmod 755 .cdf/semver
         TAG_VERSION=$(.cdf/semver calculate --path $PWD)
-        cat semver.log
         TAG_NAME="v$TAG_VERSION"
-        GIT_REF=$(git rev-parse HEAD)
-        RESPONSE=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" \
-          -H "Content-Type: application/json" \
-          -X POST \
-          -d "{\"tag\":\"$TAG_NAME\",\"message\":\"$TAG_NAME\",\"object\":\"$GIT_REF\",\"type\":\"commit\"}" \
-          "https://api.github.com/repos/$GITHUB_REPOSITORY/git/tags")
-        TAG_SHA=$(echo "$RESPONSE" | jq -r '.sha')
-        if [ "$TAG_SHA" == "" ]; then
-          echo "RESPONSE=$RESPONSE"
-          echo "Failed to create tag"
-          exit 1
-        fi
-        RESPONSE=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" \
-          -H "Content-Type: application/json" \
-          -X POST \
-          -d "{\"ref\":\"refs/tags/$TAG_NAME\",\"sha\":\"$TAG_SHA\"}" \
-          "https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs")
-        REF=$(echo "$RESPONSE" | jq -r '.ref')
-        if [ "$REF" = "" ]; then
-          echo "RESPONSE=$RESPONSE"
-          echo "Failed to create ref"
-          exit 1
-        fi
+        TAG_SHA=$(git rev-parse HEAD)
+        # GIT_REF=$(git rev-parse HEAD)
+        # RESPONSE=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" \
+        #   -H "Content-Type: application/json" \
+        #   -X POST \
+        #   -d "{\"tag\":\"$TAG_NAME\",\"message\":\"$TAG_NAME\",\"object\":\"$GIT_REF\",\"type\":\"commit\"}" \
+        #   "https://api.github.com/repos/$GITHUB_REPOSITORY/git/tags")
+        # TAG_SHA=$(echo "$RESPONSE" | jq -r '.sha')
+        # if [ "$TAG_SHA" == "" ]; then
+        #   echo "RESPONSE=$RESPONSE"
+        #   echo "Failed to create tag"
+        #   exit 1
+        # fi
+        # RESPONSE=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" \
+        #   -H "Content-Type: application/json" \
+        #   -X POST \
+        #   -d "{\"ref\":\"refs/tags/$TAG_NAME\",\"sha\":\"$TAG_SHA\"}" \
+        #   "https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs")
+        # REF=$(echo "$RESPONSE" | jq -r '.ref')
+        # if [ "$REF" = "" ]; then
+        #   echo "RESPONSE=$RESPONSE"
+        #   echo "Failed to create ref"
+        #   exit 1
+        # fi
         echo "TAG_VERSION=$TAG_VERSION"
         echo "TAG_NAME=$TAG_NAME"
         echo "TAG_SHA=$TAG_SHA"
         echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_ENV"
         echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
         echo "TAG_SHA=$TAG_SHA" >> "$GITHUB_ENV"
+
+        git config user.name github-actions
+        git config user.email github-actions@github.com
+        git tag $TAG_NAME
+        git push --tags
