fix: .git permission nonsense
Add sudo permissions check before fetching tags.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -42,6 +42,7 @@ runs:
       id: tag
       shell: bash
       run: |
+        sudo chmod -R a+rX .git || echo "Invalid sudo permissions"
         git fetch --tags
         if [ "${{ github.event_name }}" == "pull_request" ]; then
           echo "Skipping tag creation for pull requests, calculating release candidate tag."
